version: '3.6'

services:
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:v0.12.0
    ports:
      - '9089:5001' # ipfs api - expose if needed/wanted
      - '9081:8080' # ipfs gateway - expose if needed/wanted
